[build-system]
requires = ["setuptools>=45", "wheel", "setuptools-scm>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.check-manifest]
ignore = [
  ".pre-commit-config.yaml",
  "test/**/*",
  "docs/**/*",
  "examples/**/*",
  "CHANGELOG.md",
]
