{% set name = "pycudadecon" %}
{% set setupdata = load_setup_py_data() %}

package:
  name: {{ name }}
  {% if environ.get('BRANCH') == "develop" %}
  version: "{{ GIT_DESCRIBE_TAG }}_{{ GIT_BUILD_STR }}"
  {% else %}
  version: {{ setupdata.get('version') }}
  {% endif %}

source:
  # path: ..
  git_url: https://github.com/tlambert03/pycudadecon
  git_rev: "{{ environ.get('BRANCH') }}"

build:
  number: 0
  string: 'py{{ PY_VER|replace(".", "") }}_{{ PKG_BUILDNUM }}'
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - tifffile >=0.14.0
    - llspylibs >=0.2.0

test:
  requires:
    # - pytest
    # - pytest-qt
    # - llscd
  imports:
    - pycudadecon # [not py2k]

about:
  home: {{ setupdata.get('url') }}
  license: {{ setupdata.get('license') }}
  license_file: LICENSE
  summary: {{ setupdata.get('description') }}
