name: test and deploy

on:
  push:
    branches:
      - master
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  # Won't work without GPU

  # test:
  #   name: ${{ matrix.platform }} (${{ matrix.python-version }})
  #   runs-on: ${{ matrix.platform }}
  #   defaults:
  #     run:
  #       shell: bash -l {0}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       python-version: [3.7, 3.8, 3.9]
  #       platform: [ubuntu-latest, windows-latest]
  #   steps:
  #     - uses: actions/checkout@v2

  #     - uses: conda-incubator/setup-miniconda@v2
  #       with:
  #         mamba-version: "*"
  #         channels: conda-forge,defaults
  #         channel-priority: true
  #         python-version: ${{ matrix.python-version }}

  #     - name: Print info
  #       run: |
  #         conda info
  #         conda list
  #         conda config --show-sources
  #         conda config --show
  #         printenv | sort

  #     - name: Install
  #       run: |
  #         mamba install cudadecon>=0.0.11 pytest
  #         pip install -e .

  #     - name: Test
  #       run: pytest

  # - name: Coverage
  #   uses: codecov/codecov-action@v1

  deploy:
    # needs: test
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'tlambert03/pycudadecon' && contains(github.ref, 'tags') }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel twine
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_API_KEY }}
        run: |
          git tag
          python setup.py sdist bdist_wheel
          twine upload dist/*
